export const BRAND_FILTERS = {
  ALL: "all",
  NIKE: "Nike",
  ADIDAS: "Adidas",
  PUMA: "Puma",
  VANS: "Vans",
  REEBOK: "Reebok",
  CONVERSE: "Converse",
  NEWBALANCE: "New Balance",
};
export const items = [
  {
    id: 1,
    title: "Nike Air Force 1 Mid",
    img: "1.webp",
    description: "Zapatillas Nike para hombre",
    price: "89.999",
    brand: BRAND_FILTERS.NIKE,
    detail: "1.1.webp",
  },
  {
    id: 2,
    title: "Air Jordan 1 Low SE",
    img: "2.webp",
    description: "Zapatillas Nike para hombre",
    price: "82.999",
    brand: BRAND_FILTERS.NIKE,
    detail: "2.1.webp",
  },
  {
    id: 3,
    title: "Jordan Max Aura 4",
    img: "3.webp",
    description: "Zapatillas Nike para hombre",
    price: "80000",
    brand: BRAND_FILTERS.NIKE,
    detail: "3.1.webp",
  },
  {
    id: 4,
    title: "Nike Air Max 90",
    img: "4.webp",
    description: "Zapatillas Nike para hombre",
    price: "110000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "4.1.webp",
  },
  {
    id: 5,
    title: "Nike Air Max 97",
    img: "5.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "5.1.webp",
  },
  {
    id: 6,
    title: "Air Jordan 1 Low",
    img: "6.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
    detail: "6.1.webp",
  },
  {
    id: 7,
    title: "Air Jordan 5 Retro SE",
    img: "7.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
    detail: "7.1.webp",
  },
  {
    id: 8,
    title: "Jumpman Two Trey",
    img: "8.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
    detail: "8.1.webp",
  },
  {
    id: 9,
    title: "Nike Air Max 90 SE",
    img: "9.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "9.1.webp",
  },
  {
    id: 10,
    title: "Nike Air Huarache",
    img: "10.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "10.1.webp",
  },
];
export const acordeonItems = [
  {
    title: "Devoluciones y envíos",
    content:
      "Entregas a todo el país.Podés devolver tu pedido por cualquier motivo, sin cargo, dentro de un plazo de 30 días.",
  },
  {
    title: "Métodos de pago",
    content:
      "Aceptamos las siguientes opciones de pago: Tarjetas de Crédito, Tarjetas de Débito y Mercado Pago.",
  },
  // Agrega más elementos según necesites
];
