export const BRAND_FILTERS = {
  ALL: "all",
  NIKE: "Nike",
  ADIDAS: "Adidas",
  PUMA: "Puma",
  VANS: "Vans",
  REEBOK: "Reebok",
  CONVERSE: "Converse",
  NEWBALANCE: "New Balance",
};
export const items = [
  {
    id: 1,
    title: "Air max 97",
    img: "4.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 2,
    title: "Air max 97",
    img: "3.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 3,
    title: "Air max 97",
    img: "2.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 4,
    title: "Air max 97",
    img: "1.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
  },
  {
    id: 5,
    title: "Air max 97",
    img: "1.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
  },
  {
    id: 6,
    title: "Air max 97",
    img: "4.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 7,
    title: "Air max 97",
    img: "3.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 8,
    title: "Air max 97",
    img: "2.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
  },
  {
    id: 9,
    title: "Air max 97",
    img: "1.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
  },
  {
    id: 10,
    title: "Air max 97",
    img: "1.webp",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.CONVERSE,
  },
];
