export const BRAND_FILTERS = {
  ALL: "all",
  NIKE: "Nike",
  ADIDAS: "Adidas",
  PUMA: "Puma",
  VANS: "Vans",
  REEBOK: "Reebok",
  CONVERSE: "Converse",
  NEWBALANCE: "New Balance",
};

export const items = [
  {
    id: 1,
    title: "Nike Air Force 1 Mid",
    img: "1.png",
    description: "Zapatillas Nike para hombre",
    price: "90000",
    brand: BRAND_FILTERS.NIKE,
    detail: "1.1.png",
  },
  {
    id: 2,
    title: "Air Jordan 1 Low SE",
    img: "2.png",
    description: "Zapatillas Nike para hombre",
    price: "83000",
    brand: BRAND_FILTERS.NIKE,
    detail: "2.1.png",
  },
  {
    id: 3,
    title: "Jordan Max Aura 4",
    img: "3.png",
    description: "Zapatillas Nike para hombre",
    price: "80000",
    brand: BRAND_FILTERS.NIKE,
    detail: "3.1.png",
  },
  {
    id: 4,
    title: "Nike Air Max 90",
    img: "4.png",
    description: "Zapatillas Nike para hombre",
    price: "110000",
    brand: BRAND_FILTERS.NIKE,
    detail: "4.1.png",
  },
  {
    id: 5,
    title: "Nike Air Max 97",
    img: "5.png",
    description: "Zapatillas Nike para hombre",
    price: "150000",
    brand: BRAND_FILTERS.NIKE,
    detail: "5.1.png",
  },
  // {
  //   id: 6,
  //   title: "Air Jordan 1 Low",
  //   img: "6.png",
  //   description: "Zapatillas Nike para hombre",
  //   price: "150000",
  //   brand: BRAND_FILTERS.NIKE,
  //   detail: "6.1.png",
  // },
  // {
  //   id: 7,
  //   title: "Air Jordan 5 Retro SE",
  //   img: "7.png",
  //   description: "Zapatillas Nike para hombre",
  //   price: "150000",
  //   brand: BRAND_FILTERS.NIKE,
  //   detail: "7.1.png",
  // },
  // {
  //   id: 8,
  //   title: "Jumpman Two Trey",
  //   img: "8.png",
  //   description: "Zapatillas Nike para hombre",
  //   price: "150000",
  //   brand: BRAND_FILTERS.NIKE,
  //   detail: "8.1.png",
  // },
  // {
  //   id: 9,
  //   title: "Nike Air Max 90 SE",
  //   img: "9.png",
  //   description: "Zapatillas Nike para hombre",
  //   price: "150000",
  //   brand: BRAND_FILTERS.NIKE,
  //   detail: "9.1.png",
  // },
  // {
  //   id: 10,
  //   title: "Nike Air Huarache",
  //   img: "10.png",
  //   description: "Zapatillas Nike para hombre",
  //   price: "150000",
  //   brand: BRAND_FILTERS.NIKE,
  //   detail: "10.1.png",
  // },
  {
    id: 12,
    title: "YZY 350 V2 CMPCT",
    img: "12.png",
    description: "Zapatillas Adidas unisex",
    price: "123000",
    brand: BRAND_FILTERS.ADIDAS,
    popular: "popular",
    detail: "12.1.png",
  },
  {
    id: 13,
    title: "Yeezy Boost 350 V2",
    img: "13.png",
    description: "Zapatillas Adidas unisex",
    price: "123000",
    brand: BRAND_FILTERS.ADIDAS,
    detail: "13.1.png",
  },
  {
    id: 14,
    title: "All Star BB SHIFT",
    img: "14.png",
    description: "Zapatillas Conserse unisex",
    price: "123000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "14.1.png",
  },
  {
    id: 15,
    title: "Pro Blaze V2 Mid",
    img: "15.png",
    description: "Zapatillas Conserse unisex",
    price: "53000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "15.1.png",
  },
  {
    id: 16,
    title: "Pro Blaze V2 Mid",
    img: "16.png",
    description: "Zapatillas Conserse unisex",
    price: "53000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "16.1.png",
  },
  {
    id: 17,
    title: "Chuck Taylor All Star",
    img: "17.png",
    description: "Zapatillas Conserse unisex",
    price: "38000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "17.1.png",
  },
  {
    id: 18,
    title: "Chuck Taylor All Star",
    img: "18.png",
    description: "Zapatillas Conserse unisex",
    price: "39000",
    brand: BRAND_FILTERS.CONVERSE,
    detail: "18.1.png",
  },
  {
    id: 19,
    title: "CA Pro Classic",
    img: "19.png",
    description: "Zapatillas Puma unisex",
    price: "41500",
    brand: BRAND_FILTERS.PUMA,
    detail: "19.1.png",
  },
  {
    id: 20,
    title: "CA Pro Classic",
    img: "20.png",
    description: "Zapatillas Puma unisex",
    price: "41500",
    brand: BRAND_FILTERS.PUMA,
    detail: "20.1.png",
  },
  {
    id: 21,
    title: "Suede Classic XXI ADP",
    img: "21.png",
    description: "Zapatillas Puma unisex",
    price: "37500",
    brand: BRAND_FILTERS.PUMA,
    detail: "21.1.png",
  },
  {
    id: 22,
    title: "Softride Premier ADP",
    img: "22.png",
    description: "Zapatillas Puma unisex",
    price: "37750",
    brand: BRAND_FILTERS.PUMA,
    detail: "22.1.png",
  },
  {
    id: 23,
    title: "Voyage NITRO 2",
    img: "23.png",
    description: "Zapatillas Puma para hombre",
    price: "61500",
    brand: BRAND_FILTERS.PUMA,
    detail: "23.1.png",
  },
  {
    id: 24,
    title: "U OLD SKOOL",
    img: "24.png",
    description: "Zapatillas Vans unisex",
    price: "42000",
    brand: BRAND_FILTERS.VANS,
    detail: "24.1.png",
  },
  {
    id: 25,
    title: "U SK8-MID REISSUE",
    img: "25.png",
    description: "Zapatillas Vans unisex",
    price: "42500",
    brand: BRAND_FILTERS.VANS,
    detail: "25.1.png",
  },
  {
    id: 26,
    title: "U SK8-HI",
    img: "26.png",
    description: "Zapatillas Vans unisex",
    price: "46500",
    brand: BRAND_FILTERS.VANS,
    detail: "26.1.png",
  },
  {
    id: 27,
    title: "U Authentic 44 DX",
    img: "27.png",
    description: "Zapatillas Vans unisex",
    price: "31000",
    brand: BRAND_FILTERS.VANS,
    detail: "27.1.png",
  },
  {
    id: 28,
    title: "U SK8-Low",
    img: "28.png",
    description: "Zapatillas Vans unisex",
    price: "42000",
    brand: BRAND_FILTERS.VANS,
    detail: "28.1.png",
  },  
  {
    id: 29,
    title: "480",
    img: "29.png",
    description: "Zapatillas New Balance unisex",
    price: "67500",
    brand: BRAND_FILTERS.NEWBALANCE,
    detail: "29.1.png",
  },
  {
    id: 30,
    title: "Fresh Foam More Trail v3",
    img: "30.png",
    description: "Zapatillas New Balance para hombre",
    price: "120000",
    brand: BRAND_FILTERS.NEWBALANCE,
    detail: "30.1.png",
  },
  {
    id: 31,
    title: "550",
    img: "31.png",
    description: "Zapatillas New Balance kids",
    price: "82500",
    brand: BRAND_FILTERS.NEWBALANCE,
    detail: "31.1.png",
  },
  {
    id: 32,
    title: "574",
    img: "32.png",
    description: "Zapatillas New Balance para hombre",
    price: "56250",
    brand: BRAND_FILTERS.NEWBALANCE,
    detail: "32.1.png",
  },  
  {
    id: 33,
    title: "9060",
    img: "33.png",
    description: "Zapatillas New Balance unisex",
    price: "120000",
    brand: BRAND_FILTERS.NEWBALANCE,
    detail: "33.1.png",
  },  
  {
    id: 34,
    title: "RUNFALCON 3.0",
    img: "34.png",
    description: "Zapatillas Adidas unisex",
    price: "42500",
    brand: BRAND_FILTERS.ADIDAS,
    detail: "34.1.png",
  },  
  {
    id: 35,
    title: "SUPERSTAR",
    img: "35.png",
    description: "Zapatillas Adidas unisex",
    price: "88000",
    brand: BRAND_FILTERS.ADIDAS,
    detail: "35.1.png",
  },
  {
    id: 36,
    title: "Energen Lite",
    img: "36.png",
    description: "Zapatillas Reebok unisex",
    price: "90000",
    brand: BRAND_FILTERS.REEBOK,
    detail: "36.1.png",
  },
  {
    id: 37,
    title: "New Pervader",
    img: "37.png",
    description: "Zapatillas Reebok unisex",
    price: "32000",
    brand: BRAND_FILTERS.REEBOK,
    detail: "37.1.png",
  },
  {
    id: 38,
    title: "Speed 22 TR",
    img: "38.png",
    description: "Zapatillas Reebok unisex",
    price: "60000",
    brand: BRAND_FILTERS.REEBOK,
    detail: "38.1.png",
  },
  {
    id: 39,
    title: "Reebok Glide",
    img: "39.png",
    description: "Zapatillas Reebok unisex",
    price: "50000",
    brand: BRAND_FILTERS.REEBOK,
    detail: "39.1.png",
  },
  {
    id: 40,
    title: "Zig Kinetica 3",
    img: "40.png",
    description: "Zapatillas Reebok para hombre",
    price: "80000",
    brand: BRAND_FILTERS.REEBOK,
    detail: "40.1.png",
  },  

];
export const acordeonItems = [
  {
    title: "Devoluciones y envíos",
    content:
      "Entregas a todo el país.Podés devolver tu pedido por cualquier motivo, sin cargo, dentro de un plazo de 30 días.",
  },
  {
    title: "Métodos de pago",
    content:
      "Aceptamos las siguientes opciones de pago: Tarjetas de Crédito, Tarjetas de Débito y Mercado Pago.",
  },
 
];
